### ISSUE TITLE
How to adapt to other size pictures like 512x512?

### ISSUE THREAD

**Issue by ywz978020607** [teddykoker/unsupervised-deep-homography#6]
Hello,thanks for your codes about UDH.
I have a question: How to adapt to other size pictures like 512x512?
Should I change the Net or change the STD and Mean values?

**Comment by teddykoker** [comment]
Hey there,

In order to adapt the code for larger images you will need to make a few changes:

1. In `datasets.py`, change the resize and center crop values to `512` instead of `256`, change the patch size to what you would like to use.

2. In `model.py` you will need to make some changed to the architecture to make whatever `patch_size` you choose work. In my case a 128x128 patch used 3 `MaxPool2d(2, 2)` to downsample into 16x16 with 128 channels. With larger patches, you will need to either add more downsampling, or have a larger input to the fully connected layer at the end.

On the other hand, if you just want to use larger images, but the same patch size, you can use the code as is and it should work fine!

**Comment by ywz978020607** [comment]
Thanks for answering!

**Comment by ywz978020607** [comment]
And I found a easier way:
first, resize pictures to 256*256, and use 256*256 and 128*128 combination, get corners and delta, then resize the corners to adapt the true data, get the real Homography Matrix.
